#version: '2'

#services:
#  app:
#    image: 'bank:latest'
#    build:
#      context: .
#    container_name: bank
#    depends_on:
#      - db
#      - kafka
#      - zookeeper
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bank
#      - SPRING_DATASOURCE_USERNAME=postres
#      - SPRING_DATASOURCE_PASSWORD=password
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#
#  db:
#    image: 'postgres:13.1-alpine'
#    container_name: db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password
#  zookeeper:
#    image: confluentinc/cp-zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: confluentinc/cp-kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      #      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_BROKER_ID=0
      #      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #    depends_on:
  #      - zookeeper

  postgres:
    build: postgres/
    image: postgres:13.1-alpine
    #command:
    ports:
      - "54301:5432"