server:
  port: 9000

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
  application:
    name: bank
  servlet:
    multipart:
      max-file-size: 1MB
  datasource:
    hikari:
      auto-commit: false




    producer:
      bootstrap-servers: localhost:9092

spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bank?createDatabaseIfNotExist=true
spring.datasource.username: postgres
spring.datasource.password: password

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.dll-auto: validate
spring.jpa.show-sql: true

spring.liquibase:
  enabled: true
  drop-first: false
  parameters:
    schema: bank
  default-schema: bank
  liquibase-schema: bank
  changeLog: classpath:db/changelog/db.changelog-master.xml
